import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../../lib/supabase/client'
import { formatCurrency } from "../../lib/currency/format";
import {getOfflineQueue,installOfflineSync} from '../../features/offline/offlineQueue'
const tabs=['overview','inventory','purchasing','suppliers','kitchen','automation','offline']
export default function OperationsHubPage(){
 const[tab,setTab]=useState('overview'),[inventory,setInventory]=useState([]),[suppliers,setSuppliers]=useState([]),[kitchen,setKitchen]=useState([]),[summary,setSummary]=useState(null),[queue,setQueue]=useState([]),[loading,setLoading]=useState(true)
 async function load(){setLoading(true);const[i,s,k,q]=await Promise.all([supabase.from('inventory_items').select('*').eq('is_active',true).order('name'),supabase.from('suppliers').select('*').eq('is_active',true).order('name'),supabase.from('kitchen_tickets').select('*,orders(order_number,customer_name)').in('status',['queued','preparing','ready']).order('priority',{ascending:false}).order('queued_at'),getOfflineQueue()]);setInventory(i.data||[]);setSuppliers(s.data||[]);setKitchen(k.data||[]);setQueue(q||[]);const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});const{data}=await supabase.from('daily_sales_summaries').select('*').eq('business_date',today).maybeSingle();setSummary(data);setLoading(false)}
 async function generateSummary(){await supabase.rpc('generate_daily_sales_summary');await load()}
 useEffect(()=>{
  const sync=()=>{load()}
  const cleanup=installOfflineSync(sync)
  queueMicrotask(load)
  return cleanup
},[])
 const lowStock=useMemo(()=>inventory.filter(x=>Number(x.current_stock)<=Number(x.min_stock)),[inventory])
 if(loading)return <div className="p-6">Loading operations...</div>
 return <div className="space-y-5"><div><p className="text-xs uppercase tracking-[0.2em] text-gray-400">COREÉATERY Business OS</p><h1 className="mt-1 text-3xl font-bold">Operations Hub</h1><p className="mt-2 text-sm text-gray-500">POS, inventory, purchasing, kitchen, automation, mobile dan offline operation.</p></div>
 <div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm ${tab===x?'bg-gray-950 text-white':'bg-gray-100 text-gray-700'}`}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>
 {tab==='overview'&&<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric t="Low Stock" v={lowStock.length} d/><Metric t="Suppliers" v={suppliers.length}/><Metric t="Kitchen Queue" v={kitchen.length}/><Metric t="Offline Queue" v={queue.length}/><div className="sm:col-span-2 xl:col-span-4 rounded-2xl border border-gray-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-medium">Daily Sales</p><p className="mt-1 text-2xl font-bold">{formatCurrency(summary?.total_sales||0)}</p></div><button onClick={generateSummary} className="rounded-xl bg-gray-950 px-4 py-2 text-sm text-white">Generate Closing Summary</button></div></div></div>}
 {tab==='inventory'&&<section className="rounded-2xl border border-gray-200 bg-white overflow-hidden"><div className="p-5"><h2 className="font-semibold">Inventory</h2><p className="text-sm text-gray-500">Stock, minimum level, cost dan low-stock detection.</p></div><div className="overflow-auto"><table className="min-w-full text-sm"><thead><tr className="border-y bg-gray-50 text-left"><th className="p-3">Item</th><th className="p-3">SKU</th><th className="p-3">Stock</th><th className="p-3">Min</th><th className="p-3">Status</th></tr></thead><tbody>{inventory.map(x=><tr key={x.id} className="border-b"><td className="p-3 font-medium">{x.name}</td><td className="p-3">{x.sku||'-'}</td><td className="p-3">{x.current_stock} {x.unit}</td><td className="p-3">{x.min_stock}</td><td className={`p-3 ${Number(x.current_stock)<=Number(x.min_stock)?'text-red-600 font-semibold':'text-green-600'}`}>{Number(x.current_stock)<=Number(x.min_stock)?'LOW':'OK'}</td></tr>)}</tbody></table></div></section>}
 {tab==='suppliers'&&<Panel title="Suppliers"><div className="space-y-2">{suppliers.map(x=><div key={x.id} className="rounded-xl bg-gray-50 p-3"><b>{x.name}</b><div className="text-xs text-gray-500">{x.contact_name||''} {x.phone||''} {x.email||''}</div></div>)}</div></Panel>}
 {tab==='purchasing'&&<Panel title="Purchasing"><p className="text-sm text-gray-500">Purchase-order schema is active. The next UI can operate directly on purchase_orders and purchase_order_items.</p></Panel>}
 {tab==='kitchen'&&<div className="grid gap-3 md:grid-cols-3">{['queued','preparing','ready'].map(st=><div key={st} className="rounded-2xl border border-gray-200 bg-white p-4"><h2 className="font-semibold capitalize">{st}</h2><div className="mt-3 space-y-2">{kitchen.filter(x=>x.status===st).map(x=><div key={x.id} className="rounded-xl bg-gray-50 p-3"><div className="font-medium">{x.orders?.order_number||x.order_id}</div><div className="text-xs text-gray-500">{x.orders?.customer_name||'Dine in'}</div></div>)}</div></div>)}</div>}
 {tab==='automation'&&<div className="grid gap-3 md:grid-cols-2"><Panel title="Shift auto-expiry"><p className="text-sm text-green-700">Active through scheduled cash-register shift logic.</p></Panel><Panel title="Low-stock alert"><p className="text-sm text-green-700">{lowStock.length} item(s) require attention.</p></Panel><Panel title="Daily sales summary"><p className="text-sm text-gray-500">Generated from paid payments.</p></Panel><Panel title="Notifications"><p className="text-sm text-gray-500">Notification storage is active.</p></Panel></div>}
 {tab==='offline'&&<Panel title={navigator.onLine?'Online':'Offline'}><p className="text-sm text-gray-500">IndexedDB queue is active. Offline orders/payments must remain pending until server acknowledgement. No offline payment is falsely marked paid.</p><div className="mt-4 rounded-xl bg-gray-50 p-4 text-sm">Pending actions: <b>{queue.length}</b></div></Panel>}
 </div>
}
function Metric({t,v,d}){return <div className="rounded-2xl border border-gray-200 bg-white p-5"><p className="text-xs uppercase tracking-widest text-gray-400">{t}</p><p className={`mt-2 text-3xl font-bold ${d&&Number(v)>0?'text-red-600':''}`}>{v}</p></div>}
function Panel({title,children}){return <div className="rounded-2xl border border-gray-200 bg-white p-5"><h2 className="font-semibold">{title}</h2><div className="mt-3">{children}</div></div>}

